steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/project_green', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/project_green']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'project-green',
      '--image', 'gcr.io/$PROJECT_ID/project_green',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
images:
  - 'gcr.io/$PROJECT_ID/project_green'
